#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Build all node configurations in "../nodeconfigs.json".
#
# Usage:
#   ./tools/build-all-nodes BUILD-DIR BUILD-STAMP [FILTER]
#
# where "FILTER" is a filter used by 'json -c FILTER' on the nodeconfigs.json
# to build.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail

TOP=$(cd $(dirname $0)/../ >/dev/null; pwd)
buildDir=$1
buildStamp=$2
filter=$3

[[ ! -d $buildDir ]] && mkdir -p $buildDir

configs=$(cat $TOP/nodeconfigs.json)
if [[ -n "$filter" ]]; then
    configs=$(echo "$configs" | json -c "$filter")
fi

numConfigs=$(echo "$configs" | json length)
for (( i=0; i<$numConfigs; i++ ))
do
    nodeConfig=$(echo "$configs" | json $i)
    nodeName=$(echo "$nodeConfig" | json version)-$(echo "$nodeConfig" | json build_tag) 
    nodeBuildDir=$buildDir/$nodeName
    if [[ ! -d $nodeBuildDir ]]; then
        $TOP/tools/build-a-node "$nodeConfig" $nodeBuildDir $buildStamp
    else
        echo "# nodeconfig $nodeName: $nodeBuildDir already exists"
    fi
done


